//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ResourceTier {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ResourceTier.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age.
        /// </summary>
        public static string AGE_COLUMN {
            get {
                return ResourceManager.GetString("AGE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @age.
        /// </summary>
        public static string AGE_PARAM {
            get {
                return ResourceManager.GetString("AGE_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgeRange.
        /// </summary>
        public static string AGE_RANGE_COLUMN {
            get {
                return ResourceManager.GetString("AGE_RANGE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ageRange.
        /// </summary>
        public static string AGE_RANGE_PARAM {
            get {
                return ResourceManager.GetString("AGE_RANGE_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AgeRange.
        /// </summary>
        public static string AGE_RANGE_TABLE {
            get {
                return ResourceManager.GetString("AGE_RANGE_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BUILD_COLUMN {
            get {
                return ResourceManager.GetString("BUILD_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @build.
        /// </summary>
        public static string BUILD_PARAM {
            get {
                return ResourceManager.GetString("BUILD_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build.
        /// </summary>
        public static string BUILD_TABLE {
            get {
                return ResourceManager.GetString("BUILD_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @comment.
        /// </summary>
        public static string COMMENT_PARAM {
            get {
                return ResourceManager.GetString("COMMENT_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string COUNTY_COLUMN {
            get {
                return ResourceManager.GetString("COUNTY_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @county.
        /// </summary>
        public static string COUNTY_PARAM {
            get {
                return ResourceManager.GetString("COUNTY_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to County.
        /// </summary>
        public static string COUNTY_TABLE {
            get {
                return ResourceManager.GetString("COUNTY_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @email.
        /// </summary>
        public static string EMAIL_PARAM {
            get {
                return ResourceManager.GetString("EMAIL_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string ETHNICITY_COLUMN {
            get {
                return ResourceManager.GetString("ETHNICITY_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @ethnicity.
        /// </summary>
        public static string ETHNICITY_PARAM {
            get {
                return ResourceManager.GetString("ETHNICITY_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string ETHNICITY_TABLE {
            get {
                return ResourceManager.GetString("ETHNICITY_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ethnicity.
        /// </summary>
        public static string ETHNICTY_COLUMN {
            get {
                return ResourceManager.GetString("ETHNICTY_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeColor.
        /// </summary>
        public static string EYE_COLOR_COLUMN {
            get {
                return ResourceManager.GetString("EYE_COLOR_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @eyecolor.
        /// </summary>
        public static string EYE_COLOR_PARAM {
            get {
                return ResourceManager.GetString("EYE_COLOR_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EyeColor.
        /// </summary>
        public static string EYE_COLOR_TABLE {
            get {
                return ResourceManager.GetString("EYE_COLOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GENDER_COLUMN {
            get {
                return ResourceManager.GetString("GENDER_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @gender.
        /// </summary>
        public static string GENDER_PARAM {
            get {
                return ResourceManager.GetString("GENDER_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string GENDER_TABLE {
            get {
                return ResourceManager.GetString("GENDER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspAllMessages.
        /// </summary>
        public static string GET_MESSAGES_PROC {
            get {
                return ResourceManager.GetString("GET_MESSAGES_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HairColor.
        /// </summary>
        public static string HAIR_COLOR_COLUMN {
            get {
                return ResourceManager.GetString("HAIR_COLOR_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @haircolor.
        /// </summary>
        public static string HAIR_COLOR_PARAM {
            get {
                return ResourceManager.GetString("HAIR_COLOR_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HairColor.
        /// </summary>
        public static string HAIR_COLOR_TABLE {
            get {
                return ResourceManager.GetString("HAIR_COLOR_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HEIGHT_COLUMN {
            get {
                return ResourceManager.GetString("HEIGHT_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @height.
        /// </summary>
        public static string HEIGHT_PARAM {
            get {
                return ResourceManager.GetString("HEIGHT_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string HEIGHT_TABLE {
            get {
                return ResourceManager.GetString("HEIGHT_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbyID.
        /// </summary>
        public static string HOBBIES_ID_COLUMN {
            get {
                return ResourceManager.GetString("HOBBIES_ID_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HobbyName.
        /// </summary>
        public static string HOBBIES_NAME_COLUMN {
            get {
                return ResourceManager.GetString("HOBBIES_NAME_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobbies.
        /// </summary>
        public static string HOBBIES_TABLE {
            get {
                return ResourceManager.GetString("HOBBIES_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdealDate.
        /// </summary>
        public static string IDEAL_DATE_COLUMN {
            get {
                return ResourceManager.GetString("IDEAL_DATE_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @idealdate.
        /// </summary>
        public static string IDEAL_DATE_PARAM {
            get {
                return ResourceManager.GetString("IDEAL_DATE_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string LOCATION_COLUMN {
            get {
                return ResourceManager.GetString("LOCATION_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @location.
        /// </summary>
        public static string LOCATION_PARAM {
            get {
                return ResourceManager.GetString("LOCATION_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @password.
        /// </summary>
        public static string PASSWORD_PARAM {
            get {
                return ResourceManager.GetString("PASSWORD_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profession.
        /// </summary>
        public static string PROFESSION_COLUMN {
            get {
                return ResourceManager.GetString("PROFESSION_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @profession.
        /// </summary>
        public static string PROFESSION_PARAM {
            get {
                return ResourceManager.GetString("PROFESSION_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelationshipStatus.
        /// </summary>
        public static string RELATIONSHIP_STATUS_COLUMN {
            get {
                return ResourceManager.GetString("RELATIONSHIP_STATUS_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @relationshipstatus.
        /// </summary>
        public static string RELATIONSHIP_STATUS_PARAM {
            get {
                return ResourceManager.GetString("RELATIONSHIP_STATUS_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RelationshipStatus.
        /// </summary>
        public static string RELATIONSHIP_STATUS_TABLE {
            get {
                return ResourceManager.GetString("RELATIONSHIP_STATUS_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string SEXUAL_ORIENTATION_COLUMN {
            get {
                return ResourceManager.GetString("SEXUAL_ORIENTATION_COLUMN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @orientation.
        /// </summary>
        public static string SEXUAL_ORIENTATION_PARAM {
            get {
                return ResourceManager.GetString("SEXUAL_ORIENTATION_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SexualOrientation.
        /// </summary>
        public static string SEXUAL_ORIENTATION_TABLE {
            get {
                return ResourceManager.GetString("SEXUAL_ORIENTATION_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @town.
        /// </summary>
        public static string TOWN_PARAM {
            get {
                return ResourceManager.GetString("TOWN_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserSettings.
        /// </summary>
        public static string USER_COOKIE {
            get {
                return ResourceManager.GetString("USER_COOKIE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspAddNewUser.
        /// </summary>
        public static string USER_CREATE_PROC {
            get {
                return ResourceManager.GetString("USER_CREATE_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserInformation.
        /// </summary>
        public static string USER_INFORMATION_TABLE {
            get {
                return ResourceManager.GetString("USER_INFORMATION_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspUserLogin.
        /// </summary>
        public static string USER_LOGIN_PROC {
            get {
                return ResourceManager.GetString("USER_LOGIN_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspUserProfile_UserID.
        /// </summary>
        public static string USER_PROFILE_ID_PROC {
            get {
                return ResourceManager.GetString("USER_PROFILE_ID_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspUserProfile_Username.
        /// </summary>
        public static string USER_PROFILE_USERNAME_PROC {
            get {
                return ResourceManager.GetString("USER_PROFILE_USERNAME_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string USER_TABLE {
            get {
                return ResourceManager.GetString("USER_TABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspUpdateUserDetails.
        /// </summary>
        public static string USER_UPDATE_PROC {
            get {
                return ResourceManager.GetString("USER_UPDATE_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @userid.
        /// </summary>
        public static string USERID_PARAM {
            get {
                return ResourceManager.GetString("USERID_PARAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uspCheckUsernameExists.
        /// </summary>
        public static string USERNAME_EXISTS_PROC {
            get {
                return ResourceManager.GetString("USERNAME_EXISTS_PROC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to @username.
        /// </summary>
        public static string USERNAME_PARAM {
            get {
                return ResourceManager.GetString("USERNAME_PARAM", resourceCulture);
            }
        }
    }
}
