DROP TABLE dbo.tblUsers
GO

CREATE TABLE dbo.tblUsers
(
	UserID INTEGER NOT NULL CONSTRAINT PK_HolidayMemID PRIMARY KEY CLUSTERED IDENTITY(1,1),
	Username NVARCHAR(20) NOT NULL,
	Password NVARCHAR(50) NOT NULL,
	Email  NVARCHAR(50) NOT NULL
)
GO

